name: PR Preview Deployment
on:
  pull_request:
    types: [opened, synchronize]
    branches: 
      - '*'
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

name: Use Node.js
uses: actions/setup-node@v2
with:
  node-version: '18'

run: npm ci
run: npm run build

name: Deploy to Render
env:
  RENDER_TOKEN: ${{ secrets.RENDER_API_KEY }}
run: |
  curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
    -H "Authorization: Bearer $RENDER_TOKEN" \
    -H "Content-Type: application/json" \
    -d '{"clearCache": "clear"}'