previews:
  pullRequests:
    enabled: true

services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development