name: Sourcery-Review

on:
  push:
    branches: [main]
  pull_request:

jobs:
  review-with-sourcery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sourcery Check
        uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}
          diff_ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || '' }}
          pr_summary: true
          pr_summary_only: true

      - name: Sourcery Analytics
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: sourcery-ai/run-sourcery-analytics-action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}